getMovies:
  handler: src/movie/getMovies/handler.default
  iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:Query
      Resource:
        Fn::GetAtt:
          - MoviesTable
          - Arn
  environment:
    TABLE_NAME:
      Ref: MoviesTable
  events:
    - http:
        method: get
        path: /v1/movies
    - http:
        method: get
        path: /v1/movies/{movieID}
#    SNS_TOPIC:
#      Ref: SubscriptionCreatedTopic
#    - Effect: Allow
#      Action: sns:Publish
#      Resource:
#        - Ref: SubscriptionCreatedTopic

addMovie:
  handler: src/movie/addMovie/handler.default
  iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:BatchWriteItem
      Resource:
        Fn::GetAtt:
          - MoviesTable
          - Arn
  environment:
    TABLE_NAME:
      Ref: MoviesTable
  events:
    - http:
        method: post
        path: /v1/movies
